language: ruby
cache: bundler
sudo: false

notifications:
  email: false

cache:
  bundler: true

addons:
  postgresql: "9.6"

bundler_args: --jobs 3 --retry 3

before_script:
  - psql -c "CREATE DATABASE blueskyv3_test;" -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load db:seed

env:
  global:
    - "RAILS_ENV=test"

rvm:
  - 2.5.1

matrix:
  fast_finish: true

jobs:
  fast_finish: true
  include:
    - stage: Static Analysis
      rvm: 2.5.1
      env:
        - "RUBOCOP=true"
      before_script: /bin/true
      script:
        - bundle exec rubocop

    - stage: Static Analysis
      rvm: 2.5.1
      env:
        - "COVERAGE=true"
      script:
        - bundle exec rake spec

#    - stage: Static Analysis
#      rvm: 2.5.0
#      env:
#        - "BRAKEMAN=true"
#      before_script: /bin/true
#      script:
#        - bundle exec brakeman -A